apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - nats.yaml
  - nats-setup-job.yaml
  - laravel.yaml
  - worker.yaml
  - runner.yaml
  - migrate-job.yaml
