apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../k8s/base

patches:
  - path: configmap-patch.yaml
  - path: laravel-patch.yaml
  - path: worker-patch.yaml
  - path: runner-patch.yaml
  - path: migrate-job-patch.yaml
