/**
 * Prompt builder for AI code review
 */

import type { ComplexityReport, ComplexityViolation, PRContext } from './types.js';

/**
 * Build the review prompt from complexity report
 */
export function buildReviewPrompt(
  report: ComplexityReport,
  prContext: PRContext,
  codeSnippets: Map<string, string>
): string {
  const { summary, files } = report;

  // Build violations summary
  const violationsByFile = Object.entries(files)
    .filter(([_, data]) => data.violations.length > 0)
    .map(([filepath, data]) => ({
      filepath,
      violations: data.violations,
      riskLevel: data.riskLevel,
    }));

  const violationsSummary = violationsByFile
    .map(({ filepath, violations, riskLevel }) => {
      const violationList = violations
        .map(
          (v) =>
            `  - ${v.symbolName} (${v.symbolType}): complexity ${v.complexity} (threshold: ${v.threshold}) [${v.severity}]`
        )
        .join('\n');
      return `**${filepath}** (risk: ${riskLevel})\n${violationList}`;
    })
    .join('\n\n');

  // Build code snippets section
  const snippetsSection = Array.from(codeSnippets.entries())
    .map(([key, code]) => {
      const [filepath, symbolName] = key.split('::');
      return `### ${filepath} - ${symbolName}\n\`\`\`\n${code}\n\`\`\``;
    })
    .join('\n\n');

  return `# Code Complexity Review Request

## Context
- **Repository**: ${prContext.owner}/${prContext.repo}
- **PR**: #${prContext.pullNumber} - ${prContext.title}
- **Files with violations**: ${violationsByFile.length}
- **Total violations**: ${summary.totalViolations} (${summary.bySeverity.error} errors, ${summary.bySeverity.warning} warnings)

## Complexity Violations Found

${violationsSummary}

## Code Snippets

${snippetsSection || '_No code snippets available_'}

## Your Task

For each violation:
1. **Explain** why this complexity is problematic in this specific context
2. **Suggest** concrete refactoring steps (not generic advice like "break into smaller functions")
3. **Prioritize** which violations are most important to address
4. If the complexity seems justified for the use case, say so

Format your response as a PR review comment with:
- A brief summary at the top (2-3 sentences)
- File-by-file breakdown with specific suggestions
- Prioritized list of recommended changes

Be concise but actionable. Focus on the highest-impact improvements.`;
}

/**
 * Build a minimal prompt when there are no violations
 */
export function buildNoViolationsMessage(prContext: PRContext): string {
  return `<!-- lien-ai-review -->
## ✅ Lien Complexity Analysis

No complexity violations found in PR #${prContext.pullNumber}.

All analyzed functions are within the configured complexity threshold.`;
}

/**
 * Format the AI review as a GitHub comment
 */
export function formatReviewComment(
  aiReview: string,
  report: ComplexityReport
): string {
  const { summary } = report;

  return `<!-- lien-ai-review -->
## 🔍 Lien AI Code Review

**Summary**: ${summary.totalViolations} complexity violation${summary.totalViolations === 1 ? '' : 's'} found (${summary.bySeverity.error} error${summary.bySeverity.error === 1 ? '' : 's'}, ${summary.bySeverity.warning} warning${summary.bySeverity.warning === 1 ? '' : 's'})

---

${aiReview}

---

<details>
<summary>📊 Analysis Details</summary>

- Files analyzed: ${summary.filesAnalyzed}
- Average complexity: ${summary.avgComplexity.toFixed(1)}
- Max complexity: ${summary.maxComplexity}

</details>

*Generated by [Lien](https://lien.dev) AI Code Review*`;
}

/**
 * Get the key for a violation (for code snippet mapping)
 */
export function getViolationKey(violation: ComplexityViolation): string {
  return `${violation.filepath}::${violation.symbolName}`;
}

/**
 * Build a prompt for generating a single line comment for a violation
 */
export function buildLineCommentPrompt(
  violation: ComplexityViolation,
  codeSnippet: string | null
): string {
  const snippetSection = codeSnippet
    ? `\n\nCode:\n\`\`\`\n${codeSnippet}\n\`\`\``
    : '';

  return `Generate a brief, actionable code review comment for this complexity violation.

**Function**: \`${violation.symbolName}\` (${violation.symbolType})
**File**: ${violation.filepath}
**Complexity**: ${violation.complexity} (threshold: ${violation.threshold})
**Severity**: ${violation.severity}
${snippetSection}

Write a 2-4 sentence comment that:
1. Briefly explains what makes this function complex
2. Suggests ONE specific refactoring approach

Be direct and actionable. No preamble. Start with the issue.
Example format: "This function has X nested conditions making it hard to test. Consider extracting Y into a separate function."`;
}

/**
 * Build a summary comment when using line-specific reviews
 */
export function buildLineSummaryComment(
  report: ComplexityReport,
  prContext: PRContext
): string {
  const { summary } = report;
  const emoji = summary.bySeverity.error > 0 ? '🔴' : '🟡';

  return `<!-- lien-ai-review -->
## ${emoji} Lien Complexity Review

Found **${summary.totalViolations}** complexity violation${summary.totalViolations === 1 ? '' : 's'} in this PR:
- ${summary.bySeverity.error} error${summary.bySeverity.error === 1 ? '' : 's'} (complexity > 2x threshold)
- ${summary.bySeverity.warning} warning${summary.bySeverity.warning === 1 ? '' : 's'} (complexity > threshold)

See inline comments below for specific suggestions.

<details>
<summary>📊 Details</summary>

- Files analyzed: ${summary.filesAnalyzed}
- Average complexity: ${summary.avgComplexity.toFixed(1)}
- Max complexity: ${summary.maxComplexity}

</details>

*[Lien](https://lien.dev) AI Code Review*`;
}

