name: 'Lien AI Code Review'
description: 'Analyze code complexity and post AI-assisted review comments'
author: 'Lien'
branding:
  icon: 'code'
  color: 'purple'

inputs:
  openrouter_api_key:
    description: 'OpenRouter API key for LLM access'
    required: true
  model:
    description: 'LLM model to use (e.g., anthropic/claude-sonnet-4, openai/gpt-4o)'
    default: 'anthropic/claude-sonnet-4'
  threshold:
    description: 'Complexity threshold for violations (default: 10)'
    default: '10'
  github_token:
    description: 'GitHub token for posting comments (defaults to github.token)'
    default: ${{ github.token }}
  enable_delta_tracking:
    description: 'Automatically track complexity changes vs base branch (requires fetch-depth: 0)'
    default: 'false'
  baseline_complexity:
    description: '[DEPRECATED] Path to baseline complexity JSON from base branch (use enable_delta_tracking instead)'
    default: ''
  block_on_new_errors:
    description: 'Post REQUEST_CHANGES when new error-level violations are found'
    default: 'false'
  enable_logic_review:
    description: 'Enable AST-powered logic review (beta) for bug and breaking change detection'
    default: 'false'
  logic_review_categories:
    description: 'Comma-separated finding categories (breaking_change,unchecked_return,missing_tests)'
    default: 'breaking_change,unchecked_return,missing_tests'

outputs:
  violations:
    description: 'Total number of complexity violations found'
  errors:
    description: 'Number of error-level violations'
  warnings:
    description: 'Number of warning-level violations'
  total_delta:
    description: 'Net complexity change (positive = worse, negative = better)'
  improved:
    description: 'Number of functions that got simpler'
  degraded:
    description: 'Number of functions that got more complex'

runs:
  using: 'node24'
  main: 'dist/index.js'
