name: 'Lien AI Code Review'
description: 'Analyze code complexity and post AI-assisted review comments'
author: 'Lien'
branding:
  icon: 'code'
  color: 'purple'

inputs:
  openrouter_api_key:
    description: 'OpenRouter API key for LLM access'
    required: true
  model:
    description: 'LLM model to use (e.g., anthropic/claude-sonnet-4, openai/gpt-4o)'
    default: 'anthropic/claude-sonnet-4'
  threshold:
    description: 'Complexity threshold for violations (default: 10)'
    default: '10'
  github_token:
    description: 'GitHub token for posting comments (defaults to github.token)'
    default: ${{ github.token }}
  review_style:
    description: 'Review style: "line" (default) for inline comments on all violations, "summary" for single comment only'
    default: 'line'
  baseline_complexity:
    description: 'Path to baseline complexity JSON from base branch (for delta calculation)'
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'

